### ISSUE TITLE
A way to immediately see where a module lives

### ISSUE THREAD

**Issue by timo** [perl6/modules.perl6.org#58] opened 2016-04-23 22:48 UTC
I'm often interested in seeing what github user is behind a given module (for example if many modules have similar names, but i'm sure i want the one by user "foo")

Sadly, the /repo/ url hides that fact from me; i'd have to open a new tab, switch to it, look at the url, close it again :(

Is there a way to make the authority visible? Is that useful for anyone besides me?

**Comment by zoffixznet** [comment] 2016-04-23 22:52
You can see the GitHub URL if you hover over the gihub icon for that dist

**Comment by zoffixznet** [comment] 2016-06-29 15:51
I'll assume the GitHub URL is sufficient and close this. If not, please re-open.

**Closed by zoffixznet** 2016-06-29 15:51 UTC

**Comment by finanalyst** [comment] 2016-06-30 02:06
The question is ambiguous. If 'lives' means on the internet, then the 
URL is sufficient. If 'lives' means where in the local system, then I 
think the question has validity. It is not easy to determine which of 
the various locations eg., ~/.perl, <install-path>/site | /vendor | * , 
the module has actually been installed.

Also, some modules appear to be installed purely in compiled form and 
references are to a SHA hash. Other modules are installed as perl6, 
which can then be inspected to determine how to use it if/when the 
documentation is incomplete.

The - I think - is not set in stone and is dependent on the installer. 
Consequently, it would be useful to have a simple way to determine for a 
concrete module where it is installed, and also if the uncompiled 
version is available locally.

**Comment by zoffixznet** [comment] 2016-06-30 02:46
Thank you for the feedback, but the Issue is about our modules.perl6.org ecosystem website. 

The question about installed modules should be answerable by the module installers ([panda](http://modules.perl6.org/repo/panda), [zef](http://modules.perl6.org/repo/zef), [redpanda](http://modules.perl6.org/repo/App::redpanda), or [ufo](http://modules.perl6.org/repo/ufo))

**Comment by niner** [comment] 2016-06-30 06:48
> It is not easy to determine which of the various locations eg., ~/.perl, <install-path>/site | /vendor | * ,
> the module has actually been installed.

I don't find it terribly complicated either. Especially since it's quite easy to put this into a script and save the typing:

perl6 -e 'my $cu = $*REPO.need(CompUnit::DependencySpecification.new(:short-name<Inline::Perl5>)); say $cu.repo; say $cu.repo.prefix.child("sources").child($cu.distribution.meta<provides><Inline::Perl5><pm><file>)'
inst#/home/nine/rakudo/install/share/perl6/site
"/home/nine/rakudo/install/share/perl6/site/sources/3B0B691884D053BE76F42DB8F36C3421FCE9FB4C".IO
nine@sphinx:~> vi /home/nine/rakudo/install/share/perl6/site/sources/3B0B691884D053BE76F42DB8F36C3421FCE9FB4C
